// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: leaf_service.proto

#include "leaf_service.pb.h"
#include "leaf_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace leafservice {

static const char* LeafService_method_names[] = {
  "/leafservice.LeafService/ProcessLeaf",
  "/leafservice.LeafService/SendPath",
};

std::unique_ptr< LeafService::Stub> LeafService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< LeafService::Stub> stub(new LeafService::Stub(channel, options));
  return stub;
}

LeafService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ProcessLeaf_(LeafService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendPath_(LeafService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status LeafService::Stub::ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::leafservice::PathResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::leafservice::LeafRequest, ::leafservice::PathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessLeaf_, context, request, response);
}

void LeafService::Stub::async::ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::leafservice::LeafRequest, ::leafservice::PathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessLeaf_, context, request, response, std::move(f));
}

void LeafService::Stub::async::ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessLeaf_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>* LeafService::Stub::PrepareAsyncProcessLeafRaw(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::leafservice::PathResponse, ::leafservice::LeafRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessLeaf_, context, request);
}

::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>* LeafService::Stub::AsyncProcessLeafRaw(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessLeafRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status LeafService::Stub::SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::leafservice::EmptyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::leafservice::PathRequest, ::leafservice::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendPath_, context, request, response);
}

void LeafService::Stub::async::SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::leafservice::PathRequest, ::leafservice::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendPath_, context, request, response, std::move(f));
}

void LeafService::Stub::async::SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendPath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>* LeafService::Stub::PrepareAsyncSendPathRaw(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::leafservice::EmptyResponse, ::leafservice::PathRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendPath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>* LeafService::Stub::AsyncSendPathRaw(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendPathRaw(context, request, cq);
  result->StartCall();
  return result;
}

LeafService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LeafService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LeafService::Service, ::leafservice::LeafRequest, ::leafservice::PathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LeafService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::leafservice::LeafRequest* req,
             ::leafservice::PathResponse* resp) {
               return service->ProcessLeaf(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      LeafService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< LeafService::Service, ::leafservice::PathRequest, ::leafservice::EmptyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](LeafService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::leafservice::PathRequest* req,
             ::leafservice::EmptyResponse* resp) {
               return service->SendPath(ctx, req, resp);
             }, this)));
}

LeafService::Service::~Service() {
}

::grpc::Status LeafService::Service::ProcessLeaf(::grpc::ServerContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status LeafService::Service::SendPath(::grpc::ServerContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace leafservice

