// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: leaf_service.proto
#ifndef GRPC_leaf_5fservice_2eproto__INCLUDED
#define GRPC_leaf_5fservice_2eproto__INCLUDED

#include "leaf_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace leafservice {

// The leaf service definition.
class LeafService final {
 public:
  static constexpr char const* service_full_name() {
    return "leafservice.LeafService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a leaf and receives a list of strings
    virtual ::grpc::Status ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::leafservice::PathResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::PathResponse>> AsyncProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::PathResponse>>(AsyncProcessLeafRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::PathResponse>> PrepareAsyncProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::PathResponse>>(PrepareAsyncProcessLeafRaw(context, request, cq));
    }
    // Sends a list of strings, no response needed
    virtual ::grpc::Status SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::leafservice::EmptyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::EmptyResponse>> AsyncSendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::EmptyResponse>>(AsyncSendPathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::EmptyResponse>> PrepareAsyncSendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::EmptyResponse>>(PrepareAsyncSendPathRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a leaf and receives a list of strings
      virtual void ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Sends a list of strings, no response needed
      virtual void SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::PathResponse>* AsyncProcessLeafRaw(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::PathResponse>* PrepareAsyncProcessLeafRaw(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::EmptyResponse>* AsyncSendPathRaw(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::leafservice::EmptyResponse>* PrepareAsyncSendPathRaw(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::leafservice::PathResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>> AsyncProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>>(AsyncProcessLeafRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>> PrepareAsyncProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>>(PrepareAsyncProcessLeafRaw(context, request, cq));
    }
    ::grpc::Status SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::leafservice::EmptyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>> AsyncSendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>>(AsyncSendPathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>> PrepareAsyncSendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>>(PrepareAsyncSendPathRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response, std::function<void(::grpc::Status)>) override;
      void ProcessLeaf(::grpc::ClientContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response, std::function<void(::grpc::Status)>) override;
      void SendPath(::grpc::ClientContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>* AsyncProcessLeafRaw(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::leafservice::PathResponse>* PrepareAsyncProcessLeafRaw(::grpc::ClientContext* context, const ::leafservice::LeafRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>* AsyncSendPathRaw(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::leafservice::EmptyResponse>* PrepareAsyncSendPathRaw(::grpc::ClientContext* context, const ::leafservice::PathRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessLeaf_;
    const ::grpc::internal::RpcMethod rpcmethod_SendPath_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a leaf and receives a list of strings
    virtual ::grpc::Status ProcessLeaf(::grpc::ServerContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response);
    // Sends a list of strings, no response needed
    virtual ::grpc::Status SendPath(::grpc::ServerContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessLeaf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessLeaf() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessLeaf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessLeaf(::grpc::ServerContext* /*context*/, const ::leafservice::LeafRequest* /*request*/, ::leafservice::PathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessLeaf(::grpc::ServerContext* context, ::leafservice::LeafRequest* request, ::grpc::ServerAsyncResponseWriter< ::leafservice::PathResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SendPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendPath() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SendPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPath(::grpc::ServerContext* /*context*/, const ::leafservice::PathRequest* /*request*/, ::leafservice::EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPath(::grpc::ServerContext* context, ::leafservice::PathRequest* request, ::grpc::ServerAsyncResponseWriter< ::leafservice::EmptyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessLeaf<WithAsyncMethod_SendPath<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ProcessLeaf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessLeaf() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::leafservice::LeafRequest, ::leafservice::PathResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::leafservice::LeafRequest* request, ::leafservice::PathResponse* response) { return this->ProcessLeaf(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessLeaf(
        ::grpc::MessageAllocator< ::leafservice::LeafRequest, ::leafservice::PathResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::leafservice::LeafRequest, ::leafservice::PathResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProcessLeaf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessLeaf(::grpc::ServerContext* /*context*/, const ::leafservice::LeafRequest* /*request*/, ::leafservice::PathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessLeaf(
      ::grpc::CallbackServerContext* /*context*/, const ::leafservice::LeafRequest* /*request*/, ::leafservice::PathResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SendPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendPath() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::leafservice::PathRequest, ::leafservice::EmptyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::leafservice::PathRequest* request, ::leafservice::EmptyResponse* response) { return this->SendPath(context, request, response); }));}
    void SetMessageAllocatorFor_SendPath(
        ::grpc::MessageAllocator< ::leafservice::PathRequest, ::leafservice::EmptyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::leafservice::PathRequest, ::leafservice::EmptyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPath(::grpc::ServerContext* /*context*/, const ::leafservice::PathRequest* /*request*/, ::leafservice::EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPath(
      ::grpc::CallbackServerContext* /*context*/, const ::leafservice::PathRequest* /*request*/, ::leafservice::EmptyResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ProcessLeaf<WithCallbackMethod_SendPath<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessLeaf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessLeaf() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessLeaf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessLeaf(::grpc::ServerContext* /*context*/, const ::leafservice::LeafRequest* /*request*/, ::leafservice::PathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SendPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendPath() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SendPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPath(::grpc::ServerContext* /*context*/, const ::leafservice::PathRequest* /*request*/, ::leafservice::EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessLeaf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessLeaf() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessLeaf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessLeaf(::grpc::ServerContext* /*context*/, const ::leafservice::LeafRequest* /*request*/, ::leafservice::PathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessLeaf(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendPath() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SendPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPath(::grpc::ServerContext* /*context*/, const ::leafservice::PathRequest* /*request*/, ::leafservice::EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendPath(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessLeaf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessLeaf() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessLeaf(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProcessLeaf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessLeaf(::grpc::ServerContext* /*context*/, const ::leafservice::LeafRequest* /*request*/, ::leafservice::PathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessLeaf(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendPath() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendPath(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendPath(::grpc::ServerContext* /*context*/, const ::leafservice::PathRequest* /*request*/, ::leafservice::EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendPath(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessLeaf : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessLeaf() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::leafservice::LeafRequest, ::leafservice::PathResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::leafservice::LeafRequest, ::leafservice::PathResponse>* streamer) {
                       return this->StreamedProcessLeaf(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessLeaf() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessLeaf(::grpc::ServerContext* /*context*/, const ::leafservice::LeafRequest* /*request*/, ::leafservice::PathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessLeaf(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::leafservice::LeafRequest,::leafservice::PathResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendPath() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::leafservice::PathRequest, ::leafservice::EmptyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::leafservice::PathRequest, ::leafservice::EmptyResponse>* streamer) {
                       return this->StreamedSendPath(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendPath(::grpc::ServerContext* /*context*/, const ::leafservice::PathRequest* /*request*/, ::leafservice::EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendPath(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::leafservice::PathRequest,::leafservice::EmptyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ProcessLeaf<WithStreamedUnaryMethod_SendPath<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ProcessLeaf<WithStreamedUnaryMethod_SendPath<Service > > StreamedService;
};

}  // namespace leafservice


#endif  // GRPC_leaf_5fservice_2eproto__INCLUDED
