// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leaf_service.proto

#include "leaf_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace leafservice {
PROTOBUF_CONSTEXPR LeafRequest::LeafRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.leaf_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LeafRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LeafRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~LeafRequestDefaultTypeInternal() {}
  union {
    LeafRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LeafRequestDefaultTypeInternal _LeafRequest_default_instance_;
PROTOBUF_CONSTEXPR PathResponse::PathResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.strings_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PathResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PathResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PathResponseDefaultTypeInternal() {}
  union {
    PathResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PathResponseDefaultTypeInternal _PathResponse_default_instance_;
PROTOBUF_CONSTEXPR PathRequest::PathRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.strings_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PathRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PathRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PathRequestDefaultTypeInternal() {}
  union {
    PathRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PathRequestDefaultTypeInternal _PathRequest_default_instance_;
PROTOBUF_CONSTEXPR EmptyResponse::EmptyResponse(
    ::_pbi::ConstantInitialized) {}
struct EmptyResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EmptyResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EmptyResponseDefaultTypeInternal() {}
  union {
    EmptyResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EmptyResponseDefaultTypeInternal _EmptyResponse_default_instance_;
}  // namespace leafservice
static ::_pb::Metadata file_level_metadata_leaf_5fservice_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_leaf_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_leaf_5fservice_2eproto = nullptr;

const uint32_t TableStruct_leaf_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::leafservice::LeafRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::leafservice::LeafRequest, _impl_.leaf_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::leafservice::PathResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::leafservice::PathResponse, _impl_.strings_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::leafservice::PathRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::leafservice::PathRequest, _impl_.strings_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::leafservice::EmptyResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::leafservice::LeafRequest)},
  { 7, -1, -1, sizeof(::leafservice::PathResponse)},
  { 14, -1, -1, sizeof(::leafservice::PathRequest)},
  { 21, -1, -1, sizeof(::leafservice::EmptyResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::leafservice::_LeafRequest_default_instance_._instance,
  &::leafservice::_PathResponse_default_instance_._instance,
  &::leafservice::_PathRequest_default_instance_._instance,
  &::leafservice::_EmptyResponse_default_instance_._instance,
};

const char descriptor_table_protodef_leaf_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022leaf_service.proto\022\013leafservice\"\033\n\013Lea"
  "fRequest\022\014\n\004leaf\030\001 \001(\005\"\037\n\014PathResponse\022\017"
  "\n\007strings\030\001 \003(\t\"\036\n\013PathRequest\022\017\n\007string"
  "s\030\001 \003(\t\"\017\n\rEmptyResponse2\227\001\n\013LeafService"
  "\022D\n\013ProcessLeaf\022\030.leafservice.LeafReques"
  "t\032\031.leafservice.PathResponse\"\000\022B\n\010SendPa"
  "th\022\030.leafservice.PathRequest\032\032.leafservi"
  "ce.EmptyResponse\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_leaf_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_leaf_5fservice_2eproto = {
    false, false, 306, descriptor_table_protodef_leaf_5fservice_2eproto,
    "leaf_service.proto",
    &descriptor_table_leaf_5fservice_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_leaf_5fservice_2eproto::offsets,
    file_level_metadata_leaf_5fservice_2eproto, file_level_enum_descriptors_leaf_5fservice_2eproto,
    file_level_service_descriptors_leaf_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_leaf_5fservice_2eproto_getter() {
  return &descriptor_table_leaf_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_leaf_5fservice_2eproto(&descriptor_table_leaf_5fservice_2eproto);
namespace leafservice {

// ===================================================================

class LeafRequest::_Internal {
 public:
};

LeafRequest::LeafRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:leafservice.LeafRequest)
}
LeafRequest::LeafRequest(const LeafRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LeafRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.leaf_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.leaf_ = from._impl_.leaf_;
  // @@protoc_insertion_point(copy_constructor:leafservice.LeafRequest)
}

inline void LeafRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.leaf_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

LeafRequest::~LeafRequest() {
  // @@protoc_insertion_point(destructor:leafservice.LeafRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LeafRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void LeafRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LeafRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:leafservice.LeafRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.leaf_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LeafRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 leaf = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.leaf_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* LeafRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:leafservice.LeafRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 leaf = 1;
  if (this->_internal_leaf() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_leaf(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:leafservice.LeafRequest)
  return target;
}

size_t LeafRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:leafservice.LeafRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 leaf = 1;
  if (this->_internal_leaf() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_leaf());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LeafRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LeafRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LeafRequest::GetClassData() const { return &_class_data_; }


void LeafRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LeafRequest*>(&to_msg);
  auto& from = static_cast<const LeafRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:leafservice.LeafRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_leaf() != 0) {
    _this->_internal_set_leaf(from._internal_leaf());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LeafRequest::CopyFrom(const LeafRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:leafservice.LeafRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LeafRequest::IsInitialized() const {
  return true;
}

void LeafRequest::InternalSwap(LeafRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.leaf_, other->_impl_.leaf_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LeafRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_leaf_5fservice_2eproto_getter, &descriptor_table_leaf_5fservice_2eproto_once,
      file_level_metadata_leaf_5fservice_2eproto[0]);
}

// ===================================================================

class PathResponse::_Internal {
 public:
};

PathResponse::PathResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:leafservice.PathResponse)
}
PathResponse::PathResponse(const PathResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PathResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.strings_){from._impl_.strings_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:leafservice.PathResponse)
}

inline void PathResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.strings_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PathResponse::~PathResponse() {
  // @@protoc_insertion_point(destructor:leafservice.PathResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PathResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.strings_.~RepeatedPtrField();
}

void PathResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PathResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:leafservice.PathResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.strings_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PathResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string strings = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_strings();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "leafservice.PathResponse.strings"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PathResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:leafservice.PathResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string strings = 1;
  for (int i = 0, n = this->_internal_strings_size(); i < n; i++) {
    const auto& s = this->_internal_strings(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "leafservice.PathResponse.strings");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:leafservice.PathResponse)
  return target;
}

size_t PathResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:leafservice.PathResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string strings = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.strings_.size());
  for (int i = 0, n = _impl_.strings_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.strings_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PathResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PathResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PathResponse::GetClassData() const { return &_class_data_; }


void PathResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PathResponse*>(&to_msg);
  auto& from = static_cast<const PathResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:leafservice.PathResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.strings_.MergeFrom(from._impl_.strings_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PathResponse::CopyFrom(const PathResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:leafservice.PathResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PathResponse::IsInitialized() const {
  return true;
}

void PathResponse::InternalSwap(PathResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.strings_.InternalSwap(&other->_impl_.strings_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PathResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_leaf_5fservice_2eproto_getter, &descriptor_table_leaf_5fservice_2eproto_once,
      file_level_metadata_leaf_5fservice_2eproto[1]);
}

// ===================================================================

class PathRequest::_Internal {
 public:
};

PathRequest::PathRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:leafservice.PathRequest)
}
PathRequest::PathRequest(const PathRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PathRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.strings_){from._impl_.strings_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:leafservice.PathRequest)
}

inline void PathRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.strings_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PathRequest::~PathRequest() {
  // @@protoc_insertion_point(destructor:leafservice.PathRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PathRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.strings_.~RepeatedPtrField();
}

void PathRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PathRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:leafservice.PathRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.strings_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PathRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string strings = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_strings();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "leafservice.PathRequest.strings"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PathRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:leafservice.PathRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string strings = 1;
  for (int i = 0, n = this->_internal_strings_size(); i < n; i++) {
    const auto& s = this->_internal_strings(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "leafservice.PathRequest.strings");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:leafservice.PathRequest)
  return target;
}

size_t PathRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:leafservice.PathRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string strings = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.strings_.size());
  for (int i = 0, n = _impl_.strings_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.strings_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PathRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PathRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PathRequest::GetClassData() const { return &_class_data_; }


void PathRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PathRequest*>(&to_msg);
  auto& from = static_cast<const PathRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:leafservice.PathRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.strings_.MergeFrom(from._impl_.strings_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PathRequest::CopyFrom(const PathRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:leafservice.PathRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PathRequest::IsInitialized() const {
  return true;
}

void PathRequest::InternalSwap(PathRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.strings_.InternalSwap(&other->_impl_.strings_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PathRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_leaf_5fservice_2eproto_getter, &descriptor_table_leaf_5fservice_2eproto_once,
      file_level_metadata_leaf_5fservice_2eproto[2]);
}

// ===================================================================

class EmptyResponse::_Internal {
 public:
};

EmptyResponse::EmptyResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:leafservice.EmptyResponse)
}
EmptyResponse::EmptyResponse(const EmptyResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  EmptyResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:leafservice.EmptyResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData EmptyResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*EmptyResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata EmptyResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_leaf_5fservice_2eproto_getter, &descriptor_table_leaf_5fservice_2eproto_once,
      file_level_metadata_leaf_5fservice_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace leafservice
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::leafservice::LeafRequest*
Arena::CreateMaybeMessage< ::leafservice::LeafRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::leafservice::LeafRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::leafservice::PathResponse*
Arena::CreateMaybeMessage< ::leafservice::PathResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::leafservice::PathResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::leafservice::PathRequest*
Arena::CreateMaybeMessage< ::leafservice::PathRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::leafservice::PathRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::leafservice::EmptyResponse*
Arena::CreateMaybeMessage< ::leafservice::EmptyResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::leafservice::EmptyResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
